# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master



pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(783128f5-f4d2-4f2c-bfe4-1d2af23c8de0)'
    azureContainerRegistry: '{"loginServer":"dockkafkacr.azurecr.io", "id" : "/subscriptions/783128f5-f4d2-4f2c-bfe4-1d2af23c8de0/resourceGroups/resgrg/providers/Microsoft.ContainerRegistry/registries/dockkafkacr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run services'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(783128f5-f4d2-4f2c-bfe4-1d2af23c8de0)'
    subscriptionId: '783128f5-f4d2-4f2c-bfe4-1d2af23c8de0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vm-kafka3_group'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://greencoin2020@dev.azure.com/greencoin2020/Greencoin_project/_git/Greencoin_project/docker-compose.yml'
    deploymentMode: 'Incremental'