# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- deployment: VMDeploy
  displayName: kafka_containers
  environment:
    name: vm2v8
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'id_rsa'
              sourceFolder: 'https://github.com/Roccolib/discourse/blob/master'
              contents: 'docker-compose.yml'
              readyTimeout: '20000'
         
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'Azure subscription 1(783128f5-f4d2-4f2c-bfe4-1d2af23c8de0)'
              azureContainerRegistry: '{"loginServer":"dockkafkacr.azurecr.io", "id" : "/subscriptions/783128f5-f4d2-4f2c-bfe4-1d2af23c8de0/resourceGroups/resgrg/providers/Microsoft.ContainerRegistry/registries/dockkafkacr"}'
              dockerComposeFile: 'docker-compose.yml'
              action: 'Run services'